captain_console/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import authenticate, login, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('captain.urls')),
    path('login/', include('login.urls')),
    # path('login/', include('django.contrib.auth.urls')),
    path('checkout/', include('checkout.urls')),
    path('signup/', include('signup.urls')),
    path('edit/', include('edit.urls')),
    path('store/', include('game.urls')),
    path('developers/', include('developer.urls')),
    path('users/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('history/', include('history.urls')),
    path('error/', include('error.urls')),
]

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #http://localhost:8000/games/
    path('', views.cart, name="cart"),

]

game/models.py
from django.db import models

# Create your models here.
from django.db import models

from developer.models import Developer


class GameCategory(models.Model):
    name = models.CharField(max_length=255)


class Game(models.Model):
    name = models.CharField(max_length=255)
    image = models.CharField(max_length=999, blank=True)
    description = models.CharField(max_length=999, blank=True)
    category = models.ForeignKey(GameCategory, on_delete=models.CASCADE)
    price = models.FloatField()
    on_sale = models.BooleanField()
    developer = models.ForeignKey(Developer, on_delete=models.CASCADE)
    def __str__(self):
        return self.name


class GameImage(models.Model):
    image = models.CharField(max_length=999)
    game = models.ForeignKey(Game, on_delete=models.CASCADE)


#history fyrir neðan

#from django.contrib.contenttypes.models import  import ContentType
#from django.contrib.contenttypes.fields import  import GenericForeignKEy
#from django.conf import settings

#User = settings.AUTH_USER_MODEL

#class History(models.Model) :
 #   user = models.ForeignKey(User, on_delete=models.CASCADE)
  #  content_type = models.ForeignKey(ContentType, on_delete=models.SET_NULL, null=True)
   # object_id = models.PositiveIntegerField()
    #content_object =GenericForeignKEy()
    #viewed_on = models.DateTimeField(auto_now_add=True)

    #def __str__(self):
    #    return self.content_object

cart/views.py
from django.shortcuts import render

# Create your views here.
def cart(request):
    return render(request, 'cart/cart.html')

templates/cart/cart.html
{% extends 'base.html' %}
{% block content %}
    {% for game_image in game.gameimage_set.all %}
{#        <img src="{{ game_image.image }}" class="game-img" />#}
{#        <img class="game-img" src="{{ game.image }}" />#}
    {% endfor %}
    <h2 class="header">Cart</h2>
    <div class="cart-game">
        <ul id="cart-items">

        </ul>
    </div>
    <h4>Total Price: </h4>
    <div id="total_price">

    </div>
    <script>
         var cartRaw = localStorage.getItem('cart');
         var cart;
         if(cartRaw === null){
             cart = [];
         }
         else{
             cart = JSON.parse(cartRaw);
         }
         var cartitems = document.getElementById("cart-items")
         var totalprice = 0;
         for(i=0; i<cart.length;i++){

             element = document.createElement("li");
             var photo_element = document.createElement("img");
             photo_element.src=cart[i].image;
             element.appendChild(photo_element);
             var name_element = document.createElement("h4");
             name_element.textContent=cart[i].name;
             element.appendChild(name_element);
             var price_element = document.createElement("h4");
             price_element.textContent=cart[i].price;
             element.appendChild(price_element);
             cartitems.appendChild(element);
             totalprice += cart[i].price;
         }
         var totalprice_element = document.getElementById("total_price")
        totalprice_element.textContent=totalprice;
    </script>

    <div class="info-btns">
        <a class="left-btn" id="previous-page" href="/store">Go back to store</a>
        <a class="right-btn" id="previous-page" href="/checkout/contact_info">Continue to checkout</a>
        <a href="/cart"><button onclick="window.localStorage.removeItem('cart')" class="clear_btn" id="previous-page">Clear cart</button></a>
    </div>
    <div>
        <br><br><br><br><br><br><br><br><br><br><br>
    </div>

{% endblock %}

templates/cart/index.html
{% extends 'base.html' %}
{% block content %}

    <div class="cart">

        <div class="table-and-buttons">
            <table class="table">
                <thead>
                    <tr>
                        <td></td>
                        <td> Product </td>
                        <td> Quantity </td>
                        <td> Price </td>
                    </tr>
                </thead>

                <tbody>
                {% for cart in carts %}

                    <tr>
                        <td>
                            <a href="/store/{{ cart.games.id }}">
                                <img class="product-img-cart" src="{{ cart.games.gameimage_set.first.image }}">
                            </a>
                        </td>

                        <td>
                            <a href="/store/{{ cart.games.id }}">
                                <h4>{{ cart.games.name }} </h4>
                            </a>
                                {{ cart.games.short_description }} <br>
                                {{ cart.games.price }} $
                        </td>

                        <td>
                            <div class="cart-quantity" id="nice-number">
                                <div class="pull-left">
                                   <button onclick="location.href='{% url 'cart-index' %}';"class="decrease-cart"
                                           id="decrease" data-id="{{ cart.id }}">-</button>
                                </div>

                                    <input id="quantity" data-id="{{ cart.games.id }}" type="number"
                                           value="{{ cart.quantity }}" disabled>

                                <div class="pull-right">
                                    <button onclick="location.href='{% url 'cart-index' %}';"class="increase-cart"
                                            id="increase" data-id="{{ cart.id }}">+</button>
                                </div>

                            </div>
                        </td>

                        <td>
                            {% for games, price in eachItemTotal.items %}
                                {% if games == cart.games.id %}
                                    {{ price }}
                                {% endif %}
                            {% endfor %}
                        </td>

                        <td>
                            <button class="bth -bth-primary remove-cart-item-btn" id="remove-cart-item-btn"
                                    data-id="{{ cart.id }}"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></button>
                        </td>

                    </tr>

                {% endfor %}

                </tbody>
                <td id="total" colspan="3"> <h4>Total:</h4></td>
                <td id="total" colspan="2"> <h4> {{ sumTotal }} </h4></td>

            </table>
            <a class="btn -btn-primary" id="previous-page" href="{% url 'game-index' %}">Go back to store</a>
            <a class="btn -btn-primary" id="contact-info" href="{% url 'checkout-index' %}">Proceed to next step</a>
        </div>
    
    </div>

{% endblock %}