captain_console/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import authenticate, login, views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('captain.urls')),
    path('login/', include('login.urls')),
    # path('login/', include('django.contrib.auth.urls')),
    path('checkout/', include('checkout.urls')),
    path('signup/', include('signup.urls')),
    path('edit/', include('edit.urls')),
    path('store/', include('game.urls')),
    path('developers/', include('developer.urls')),
    path('users/', include('user.urls')),
    path('cart/', include('cart.urls')),
    path('history/', include('history.urls')),
    path('error/', include('error.urls')),
]

cart/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #http://localhost:8000/games/
    path('', views.cart, name="cart"),

]

user/urls.py
from django.urls import path
from . import views


urlpatterns = [
    #http://localhost:8000/users/
    path('', views.index, name="user-index"),
    path('create_user', views.create_user, name="create_user"),
    path('loginpage', views.loginpage, name="loginpage"),
    path('<int:id>', views.get_user_by_id, name="user_details"),
    path('update_user/<int:id>', views.update_user, name="update_user"),

]

user/models.py
from django.db import models

from developer.models import Developer
from game.models import Game


class User(models.Model):
    image = models.CharField(max_length=999, blank=True)
    username = models.CharField(max_length=255, unique=True)
    name = models.CharField(max_length=255)
    address = models.CharField(max_length=750)
    email = models.CharField(max_length=500, unique=True)
    phoneno = models.CharField(max_length=50)


class Purchases(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_game = models.ForeignKey(Game, on_delete=models.CASCADE)
    dateofpurchase = models.DateTimeField(auto_now=True)
    amount = models.FloatField


class Basket(models.Model):
    id_user = models.ForeignKey(User, on_delete=models.CASCADE)
    id_game = models.ForeignKey(Game, on_delete=models.CASCADE)

class UserImage(models.Model):
    image = models.CharField(max_length=999)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

user/forms/forms.py
from django.forms import ModelForm, widgets
from django import forms
from user.models import User

class UserCreateForm(ModelForm):
    image = forms.CharField(required=True, widget=forms.TextInput(attrs={'class': 'form-control'}))
    class Meta:
        model = User
        exclude = ['id']
        widgets = {
            'username': widgets.TextInput(attrs={'class': 'form-control'}),
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'address': widgets.TextInput(attrs={'class': 'form-control'}),
            'email': widgets.EmailInput(attrs={'class': 'form-control'}),
            'phoneno': widgets.TextInput(attrs={'class': 'form-control'})
        }
    password = forms.CharField(required=True, label="Password",
                                 widget=forms.PasswordInput(attrs={'class': 'form-control'})
                                 )

class UserLoginPage(ModelForm):
    class Meta:
        model = User
        exclude = ['id']
        widgets = {
            'username': widgets.TextInput(attrs={'class': 'form-control'}),
            'password': widgets.TextInput(attrs={'class': 'form-control'})
        }


class UserUpdateForm(ModelForm):
    class Meta:
        model = User
        exclude = ['id']
        widgets = {
            'username'
            'name': widgets.TextInput(attrs={'class': 'form-control'}),
            'address': widgets.TextInput(attrs={'class': 'form-control'}),
            'email': widgets.TextInput(attrs={'class': 'form-control'}),
            'phoneno': widgets.NumberInput(attrs={'class': 'form-control'}),

        }

#'password': widgets.PasswordInput(attrs={'class': 'form-control'})

user/views.py
from django.shortcuts import render, get_object_or_404, redirect
from user.forms.forms import UserCreateForm, UserUpdateForm
from django.contrib.auth.models import User as DjangoUser
from user.models import User


from user.forms.forms import UserCreateForm
# Create your views here.

def index(request):
    return render(request, 'user/index.html', context={'users': User.objects.all().order_by('name')})

def create_user(request):
    if request.method == 'POST':
        form = UserCreateForm(data=request.POST)

        if form.is_valid():
            user = form.save()
            django_user = DjangoUser.objects.create_user(user.username, user.email,
                                                         form.cleaned_data['password'] )
            return redirect('user-index')
    else:
        form = UserCreateForm()

    return render(request, 'user/create_user.html', {
        'form': form
    })

def loginpage(request):
    return render(request, 'user/loginpage.html', {
    })

def get_user_by_id(request, id):
    return render(request, 'user/user_details.html', {
        'user': get_object_or_404(User, email=request.user.email)
    })

def update_user(request, id):
    instance = get_object_or_404(User, email=request.user.email)
    if request.method == 'POST':
        form = UserUpdateForm(data=request.POST, instance=instance)
        if form.is_valid():
            form.save()
            return redirect('user_details', id=id)
    else:
        form = UserUpdateForm(instance=instance)
    return render(request, 'user/update_user.html', {
        'form': form,
        'id': id
    })

templates/user/create_user.html
{% extends 'base.html' %}
{% block content %}
    <form class="form form-horizontal" action="{% url 'create_user' %}"method="POST">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Create"
               class="btn btn-primary pull-right"
               style="clear:both; margin: 10px 0" />
    </form>
{% endblock %}

templates/user/index.html
{% extends 'base.html' %}
{% block content %}
    <div class="user">
        <h2>This page shows all the user</h2>
    </div>
    <div class="users">
        {% for user in users %}
            {% include 'user/single_user.html' with user=user %}
        {% endfor %}
    </div>

{% endblock %}

templates/user/loginpage.html
{% extends "base.html" %}

{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
    <p>Your account doesn't have access to this page. To proceed,
    please login with an account that has access.</p>
    {% else %}
    <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'login' %}">
{% csrf_token %}
<table>
<tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
</tr>
<tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
</tr>
</table>

<input type="submit" value="login">
<input type="hidden" name="next" value="{{ next }}">
</form>

{# Assumes you setup the password_reset view in your URLconf #}
<p><a href="{% url 'password_reset' %}">Lost password?</a></p>

{% endblock %}

templates/user/single_user.html
<div class="well user">
    <a href="/users/{{ user.id }}">
        <!--<img class="game-img" src="{{ user.image }}" />-->
        <h4>{{ user.name }}</h4>
        <p>{{ user.address}} {{user.phoneno}} {{ user.email }}</p>

    </a>

</div>

templates/user/update_user.html
{% extends 'base.html' %}
{% block content %}
    <form class="form" action="{% url 'update_user' id %}"method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Update" class="btn btn-primary pull-right" style="clear:both; margin: 10px 0" />
    </form>
{% endblock %}

templates/user/user_details.html
{% extends "base.html" %}
{% block content %}


    {% for game_image in user.userimage_set.all %}
        <img src="{{ game_image.image }}" class="user-img" />
    {% endfor %}
    <h1>{{ user.name }}</h1>
    <p>{{ user.address }}</p>
    <p>{{ user.phoneno }}</p>
    <p>{{ user.email }}</p>

    <a href="{% url 'update_user' user.id %}" class="block btn btn-primary">Update user </a>

{% endblock %}